version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
    - "27017:27017"
  queue:
    image: rabbitmq:3-management
    ports:
    - "15672:15672"

  rabbit-setup:
    image: ruby:2.3.3
    depends_on:
    - queue
    volumes:
    - ./bundle:/usr/local/bundle
    - ./rabbit-setup:/rabbit-setup
    working_dir: /rabbit-setup
    command: sh run.sh

  content-creation-web:
    image: ruby:2.3.3
    depends_on:
    - mongo
    - queue
    ports:
    - "3000:3000"
    volumes:
    - ./bundle:/usr/local/bundle
    - ./content-creation:/content-creation
    working_dir: /content-creation
    command: sh run.sh

  news-dispatch-worker:
    image: ruby:2.3.3
    depends_on:
    - mongo
    - queue
    volumes:
    - ./bundle:/usr/local/bundle
    - ./news-dispatch:/news-dispatch
    working_dir: /news-dispatch
    command: sh work.sh

  news-dispatch-web:
    image: ruby:2.3.3
    depends_on:
    - mongo
    ports:
    - "3001:3000"
    volumes:
    - ./bundle:/usr/local/bundle
    - ./news-dispatch:/news-dispatch
    working_dir: /news-dispatch
    command: sh run.sh

  super-news-web:
    image: ruby:2.3.3
    depends_on:
    - mongo
    ports:
    - "4000:3000"
    volumes:
    - ./bundle:/usr/local/bundle
    - ./super-news:/super-news
    working_dir: /super-news
    command: sh run.sh

  super-news-worker:
    image: ruby:2.3.3
    depends_on:
    - mongo
    - queue
    volumes:
    - ./bundle:/usr/local/bundle
    - ./super-news:/super-news
    working_dir: /super-news
    command: sh work.sh

#  quick-news-web:
#    image: ruby:alpine
#    depends_on:
#    - db
#    ports:
#    - "4001:3000"
#    volumes:
#    - ./bundle:/usr/local/bundle
#    - ./quick-news:/quick-news
#    working_dir: /quick-news
#    command: sh run.sh
#
#  quick-news-worker:
#    image: ruby:alpine
#    depends_on:
#    - db
#    - queue
#    volumes:
#    - ./bundle:/usr/local/bundle
#    - ./quick-news:/quick-news
#    working_dir: /quick-news
#    command: sh work.sh
