version: '3'
services:
  db:
    image: postgres
  content-creation:
    build: dockerfiles/rails
    depends_on: 
    - db
    ports:
    - "3000:3000"
    volumes:
    - ./bundle:/bundle
    - ./content-creation:/content-creation
    working_dir: /content-creation
    command: sh run.sh
