version: '3'
services:
  # db:
  #   image: postgres
  queue:
    image: rabbitmq:3-management
    ports:
    - "15672:15672"
    volumes:
    - ./queue/etc/rabbitmq:/etc/rabbitmq
  
  # content-creation:
  #   build: dockerfiles/rails
  #   depends_on: 
  #   - db
  #   - queue
  #   ports:
  #   - "3000:3000"
  #   volumes:
  #   - ./bundle:/bundle
  #   - ./content-creation:/content-creation
  #   working_dir: /content-creation
  #   command: sh run.sh
  
  # super-news-web:
  #   build: dockerfiles/rails
  #   depends_on: 
  #   - db
  #   ports:
  #   - "4000:3000"
  #   volumes:
  #   - ./bundle:/bundle
  #   - ./super-news:/super-news
  #   working_dir: /super-news
  #   command: sh run.sh

  # super-news-worker:
  #   build: dockerfiles/rails
  #   depends_on: 
  #   - db
  #   - queue
  #   volumes:
  #   - ./bundle:/bundle
  #   - ./super-news:/super-news
  #   working_dir: /super-news
  #   command: sh work.sh
